# Generated by Django 5.1.1 on 2024-10-18 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('good_id', models.CharField(max_length=30, verbose_name='商品编号')),
                ('good_from', models.CharField(choices=[('JD', '京东'), ('SN', '苏宁'), ('A', '唯品会')], max_length=2, verbose_name='数据来源')),
                ('good_title', models.CharField(max_length=200, verbose_name='名称')),
                ('good_link', models.CharField(max_length=200, verbose_name='连接')),
                ('good_img', models.CharField(max_length=200, verbose_name='图片')),
                ('price_queue_id', models.IntegerField(default=0)),
                ('good_price0', models.CharField(max_length=30, verbose_name='价格0')),
                ('good_price1', models.CharField(max_length=30, verbose_name='价格1')),
                ('good_price2', models.CharField(max_length=30, verbose_name='价格2')),
                ('good_price3', models.CharField(max_length=30, verbose_name='价格3')),
                ('good_price4', models.CharField(max_length=30, verbose_name='价格4')),
            ],
            options={
                'verbose_name': '商品库',
                'verbose_name_plural': '商品库',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.goods')),
            ],
        ),
    ]
